gpt:
  LLM_API_URL: ${LLM_API_URL}
  LLM_API_TOKEN: ${LLM_API_TOKEN}

game:
  BASE_GROWTH: 0.1
  BASE_WEIGHT: 0.5
  BASE_RANK: 0.5
  RANK_FACTOR: 0.5
  WEIGHT_FACTOR: 0.05
  FEED_DELAY: 4
  SALO_DELAY: 8
  MAX_ITEMS: 15
  BASE_PILLS_CHANCE: 0.33
  BASE_PILLS_CHANCE_GROW: 0.75

database_url: "postgresql://avrdude:hNmfrTtKH2BBvqfsq7Bs@94.130.172.156:5432/botdb"
