services:
 rustotool:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: rustotool
   environment:
     LLM_API_URL: $LLM_API_URL
     LLM_API_TOKEN: $LLM_API_TOKEN
     DATABASE_URL: $DATABASE_URL
     TELEGRAM_TOKEN: $TELEGRAM_TOKEN
